apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gnap-genome-nexus-mongodump-pvc
  namespace: genome-nexus
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

