apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gn-ingress
  namespace: genome-nexus
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    ingress.kubernetes.io/proxy-connect-timeout: "300"
    ingress.kubernetes.io/proxy-read-timeout: "300"
    ingress.kubernetes.io/proxy-send-timeout: "300"
    # ingress.kubernetes.io/large-client-header-buffers: "4 32k"
    # increae max response size to avoid 413 errors see
    # https://github.com/kubernetes/ingress-nginx/issues/1824
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    ingress.kubernetes.io/proxy-body-size: 512m
    # add proxy protocol to header
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
spec:
  tls:
  - hosts:
    - www.genomenexus.org
    - v2.genomenexus.org
    - v1.genomenexus.org
    - grch38.genomenexus.org
    - genie.genomenexus.org
    - annotation.genomenexus.org
    - beta.genomenexus.org
    secretName: genome-nexus-v2-cert
  rules:
  - host: www.genomenexus.org
    http:
      paths:
      - path: /
        backend:
          serviceName: genome-nexus
          servicePort: http
  - host: v2.genomenexus.org
    http:
      paths:
      - path: /
        backend:
          serviceName: genome-nexus
          servicePort: http
  - host: v1.genomenexus.org
    http:
      paths:
      - path: /
        backend:
          serviceName: genome-nexus
          servicePort: http
  - host: grch38.genomenexus.org
    http:
      paths:
      - path: /
        backend:
          serviceName: genome-nexus-grch38
          servicePort: http
  - host: beta.genomenexus.org
    http:
      paths:
      - path: /
        backend:
          serviceName: genome-nexus-beta
          servicePort: http
  - host: genie.genomenexus.org
    http:
      paths:
      - path: /
        backend:
          serviceName: genome-nexus-genie
          servicePort: http
  - host: annotation.genomenexus.org
    http:
      paths:
      - path: /
        backend:
          serviceName: genome-nexus-gnap
          servicePort: http
